CREATE TABLE usuarios(
  id_user INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome  VARCHAR(255) NULL,
  login VARCHAR(255) NULL,
  senha VARCHAR(255) NULL,
  data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id_user)
);